linters:
  flake8:
    python: 3
    # stickler doesn't support 'exclude' for flake8 properly, so we disable it
    # below with files.ignore:
    # https://github.com/markstory/lint-review/issues/184
files:
  ignore:
    - doc/**/*.py
